# Generated by Django 3.2.9 on 2021-11-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_on', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('budget', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ladger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payee', models.CharField(max_length=128)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.category')),
            ],
        ),
    ]
